name: Deploy Express to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Google Auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Write service account files from secrets
        run: |
          mkdir -p ./src/config
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > ./src/config/serviceAccountKey.json
          echo '${{ secrets.GCP_STORAGE_SERVICE_ACCOUNT }}' > ./src/config/genprd-storage-bucket-service-key.json

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/genprd-images/express-backend"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        env:
          IMAGE_NAME: "asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/genprd-images/express-backend"
        run: |
          gcloud run deploy express-backend \
            --image=$IMAGE_NAME \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --memory=2Gi \
            --cpu=1 \
            --max-instances=10 \
            --set-env-vars=NODE_ENV=${{ secrets.NODE_ENV }} \
            --set-env-vars=DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --set-env-vars=DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --set-env-vars=DB_NAME=${{ secrets.DB_NAME }} \
            --set-env-vars=DB_HOST=${{ secrets.DB_HOST }} \
            --set-env-vars=DB_CONNECTION=${{ secrets.DB_CONNECTION }} \
            --set-env-vars=JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --set-env-vars=JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }} \
            --set-env-vars=REFRESH_SECRET=${{ secrets.REFRESH_SECRET }} \
            --set-env-vars=REFRESH_EXPIRATION=${{ secrets.REFRESH_EXPIRATION }} \
            --set-env-vars=GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --set-env-vars=GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            --set-env-vars=GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
            --set-env-vars=GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }} \
            --set-env-vars=GCP_FOLDER_NAME=${{ secrets.GCP_FOLDER_NAME }} \
            --set-env-vars=BASE_URL=${{ secrets.BASE_URL }} \
            --set-env-vars=FLASK_URL=${{ secrets.FLASK_URL }} \
            --set-env-vars=FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
            --set-env-vars=FIREBASE_SECRET_KEYFILE=./src/config/serviceAccountKey.json \
            --set-env-vars=GCP_STORAGE_KEYFILE=./src/config/genprd-storage-bucket-service-key.json \